-- INSERT INTO artists (name, genre)  VALUES ("Rihanna", "RnB"); 
-- INSERT INTO artists (name, genre)  VALUES ("Beyonce", "RnB"); 
-- INSERT INTO artists (name, genre)  VALUES ("The Weeknd", "Pop"); 
-- INSERT INTO artists (name, genre)  VALUES ("Bad Bunny", "Latina"); 
-- INSERT INTO artists (name, genre)  VALUES ("Kendrick Lamar", "Rap"); 
-- INSERT INTO artists (name, genre)  VALUES ("Eminem", "Rap"); 
-- INSERT INTO artists (name, genre)  VALUES ("Omah Lay", "Afro Beats"); 
-- INSERT INTO artists (name, genre)  VALUES ("Nas", "Rap"); 
-- INSERT INTO artists (name, genre)  VALUES ("Sombr", "Indie"); 
-- INSERT INTO artists (name, genre)  VALUES ("The Killers", "Band"); 
-- INSERT INTO artists (name, genre)  VALUES ("AC/DC", "Alternative"); 
-- INSERT INTO artists (name, genre)  VALUES ("Lana Del Rey", "Pop"); 
-- INSERT INTO artists (genre) VALUES ("Indie")